version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-jest-react-component
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install package dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-jest-react-component
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Upgrade yarn
          command: sudo npm install --global yarn
      - run:
          name: ESlint
          command: yarn lint
      - run:
          name: Security Check
          command: yarn audit
      - run:
          name: Test
          command: yarn test

  release:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-jest-react-component
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set Config
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Compile
          command: yarn build
      - run:
          name: Git release
          command: bash ./ci/release-git.sh
      - run:
          name: Npm release
          command: bash ./ci/release-npm.sh

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
